copy code

In [294]:
from herbie import Herbie, FastHerbie
import pandas as pd, numpy as np
import xarray as xr
import dask

In [295]:
# 0z today
run = pd.Timestamp("2026-04-06-00", tz="utc").replace(tzinfo=None).floor('24h')

In [296]:
pd.Timestamp("2026-01-25-00")

Timestamp('2026-01-25 00:00:00')

In [297]:
H = Herbie(run, model="ifs", product="oper", fxx=6, save_dir='./data/', overwrite=True)

✅ Found ┊ model=ifs ┊ product=oper ┊ 2026-Apr-06 00:00 UTC F06 ┊ GRIB2 @ google ┊ IDX @ google

In [298]:
table=H.inventory()

Downloading inventory file from self.idx='https://storage.googleapis.com/ecmwf-open-data/20260406/00z/ifs/0p25/oper/20260406000000-6h-oper-fc.index'

In [299]:
table.param.unique()

array(['asn', 'lsm', 'q', 'tcwv', 'rsn', 'sithick', 'sot', 'vsw', 'strd',
       'ssr', 'str', 'ttr', 'w', '10fg', 'ewss', 'u', 'vo', 'r', 'v',
       'gh', 'nsss', 'd', 't', 'ro', 'tp', 'sd', 'mx2t3', 'sf', 'mn2t3',
       'msl', 'sve', 'mucape', 'svn', '100u', '100v', 'zos', 'skt', 'tcc',
       '10u', 'ptype', '10v', 'tprate', '2t', '2d', 'ssrd', 'sp', 'tcw'],
      dtype=object)

In [300]:
ss = ":tp:|:2t:|:2d:|sf:|wcf:|vis:"

In [301]:
H.inventory(ss)

,grib_message,start_byte,end_byte,range,reference_time,valid_time,step,param,levelist,levtype,number,domain,expver,class,type,stream,search_this
37,38,25293503,25986430,25293503-25986430,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,tp,NaN,sfc,NaN,g,0001,od,fc,oper,:tp:sfc:g:0001:od:fc:oper
44,45,29869326,30215270,29869326-30215270,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,sf,NaN,sfc,NaN,g,0001,od,fc,oper,:sf:sfc:g:0001:od:fc:oper
94,95,72253150,72915205,72253150-72915205,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,2t,NaN,sfc,NaN,g,0001,od,fc,oper,:2t:sfc:g:0001:od:fc:oper
102,103,78139073,78826675,78139073-78826675,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,2d,NaN,sfc,NaN,g,0001,od,fc,oper,:2d:sfc:g:0001:od:fc:oper

In [302]:
ss2 = "((gh|t|u|v):(1000|850|700|500|250))"
H.inventory(ss2)

/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)

,grib_message,start_byte,end_byte,range,reference_time,valid_time,step,param,levelist,levtype,number,domain,expver,class,type,stream,search_this
18,19,12350330,13057148,12350330-13057148,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,u,500,pl,NaN,g,0001,od,fc,oper,:u:500:pl:g:0001:od:fc:oper
22,23,15917479,16656848,15917479-16656848,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,v,500,pl,NaN,g,0001,od,fc,oper,:v:500:pl:g:0001:od:fc:oper
24,25,17059476,17558321,17059476-17558321,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,gh,850,pl,NaN,g,0001,od,fc,oper,:gh:850:pl:g:0001:od:fc:oper
30,31,21816898,22416622,21816898-22416622,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,t,850,pl,NaN,g,0001,od,fc,oper,:t:850:pl:g:0001:od:fc:oper
49,50,33354931,34087747,33354931-34087747,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,u,250,pl,NaN,g,0001,od,fc,oper,:u:250:pl:g:0001:od:fc:oper
52,53,35422145,36062316,35422145-36062316,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,v,250,pl,NaN,g,0001,od,fc,oper,:v:250:pl:g:0001:od:fc:oper
86,87,64758675,65508781,64758675-65508781,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,v,850,pl,NaN,g,0001,od,fc,oper,:v:850:pl:g:0001:od:fc:oper
90,91,68286056,69013064,68286056-69013064,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,u,850,pl,NaN,g,0001,od,fc,oper,:u:850:pl:g:0001:od:fc:oper
100,101,77059902,77616893,77059902-77616893,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,gh,1000,pl,NaN,g,0001,od,fc,oper,:gh:1000:pl:g:0001:od:fc:oper
106,107,82449176,82940889,82449176-82940889,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,gh,700,pl,NaN,g,0001,od,fc,oper,:gh:700:pl:g:0001:od:fc:oper
107,108,82940889,83553689,82940889-83553689,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,t,1000,pl,NaN,g,0001,od,fc,oper,:t:1000:pl:g:0001:od:fc:oper
116,117,88557294,89101474,88557294-89101474,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,t,700,pl,NaN,g,0001,od,fc,oper,:t:700:pl:g:0001:od:fc:oper
118,119,90384977,90792943,90384977-90792943,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,gh,500,pl,NaN,g,0001,od,fc,oper,:gh:500:pl:g:0001:od:fc:oper
128,129,99612796,100229653,99612796-100229653,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,t,500,pl,NaN,g,0001,od,fc,oper,:t:500:pl:g:0001:od:fc:oper
129,130,100229653,100678811,100229653-100678811,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,gh,250,pl,NaN,g,0001,od,fc,oper,:gh:250:pl:g:0001:od:fc:oper
136,137,106531299,107148699,106531299-107148699,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,t,250,pl,NaN,g,0001,od,fc,oper,:t:250:pl:g:0001:od:fc:oper
145,146,113735059,114570433,113735059-114570433,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,v,1000,pl,NaN,g,0001,od,fc,oper,:v:1000:pl:g:0001:od:fc:oper
146,147,114570433,115408786,114570433-115408786,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,u,1000,pl,NaN,g,0001,od,fc,oper,:u:1000:pl:g:0001:od:fc:oper
152,153,120675579,121405642,120675579-121405642,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,v,700,pl,NaN,g,0001,od,fc,oper,:v:700:pl:g:0001:od:fc:oper
155,156,123216794,123924244,123216794-123924244,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,u,700,pl,NaN,g,0001,od,fc,oper,:u:700:pl:g:0001:od:fc:oper

In [303]:
fp = H.download(ss)
fp

PosixPath('data/ifs/20260406/subset_26b20944__20260406000000-6h-oper-fc.grib2')

In [304]:
ds = xr.open_dataset(fp)
ds

Ignoring index file 'data/ifs/20260406/subset_26b20944__20260406000000-6h-oper-fc.grib2.5b7b6.idx' older than GRIB file

<xarray.Dataset> Size: 17MB
Dimensions:            (latitude: 721, longitude: 1440)
Coordinates:
  * latitude           (latitude) float64 6kB 90.0 89.75 89.5 ... -89.75 -90.0
  * longitude          (longitude) float64 12kB -180.0 -179.8 ... 179.5 179.8
    time               datetime64[ns] 8B ...
    step               timedelta64[ns] 8B ...
    surface            float64 8B ...
    valid_time         datetime64[ns] 8B ...
    heightAboveGround  float64 8B ...
Data variables:
    tp                 (latitude, longitude) float32 4MB ...
    sf                 (latitude, longitude) float32 4MB ...
    t2m                (latitude, longitude) float32 4MB ...
    d2m                (latitude, longitude) float32 4MB ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-04-08T17:31 GRIB to CDM+CF via cfgrib-0.9.1...

In [305]:
filename = 'ecmwf_calm_006.nc'
ds.to_netcdf(filename)

sh: 1: getfattr: not found

In [306]:
H = FastHerbie([run], model="ifs", product="oper", fxx=np.arange(0,90,6).tolist(), save_dir='./data/', overwrite=True)

In [307]:
filepath = H.download(ss)
filepath

[PosixPath('data/ifs/20260406/subset_26efdb49__20260406000000-0h-oper-fc.grib2'),
 PosixPath('data/ifs/20260406/subset_26b20944__20260406000000-6h-oper-fc.grib2'),
 PosixPath('data/ifs/20260406/subset_26f10269__20260406000000-72h-oper-fc.grib2'),
 PosixPath('data/ifs/20260406/subset_260eb94f__20260406000000-24h-oper-fc.grib2'),
 PosixPath('data/ifs/20260406/subset_26059fc2__20260406000000-84h-oper-fc.grib2'),
 PosixPath('data/ifs/20260406/subset_265ef177__20260406000000-78h-oper-fc.grib2'),
 PosixPath('data/ifs/20260406/subset_2660db0e__20260406000000-30h-oper-fc.grib2'),
 PosixPath('data/ifs/20260406/subset_26436d03__20260406000000-60h-oper-fc.grib2'),
 PosixPath('data/ifs/20260406/subset_260e9787__20260406000000-36h-oper-fc.grib2'),
 PosixPath('data/ifs/20260406/subset_2612d2a6__20260406000000-12h-oper-fc.grib2'),
 PosixPath('data/ifs/20260406/subset_2678e5f3__20260406000000-54h-oper-fc.grib2'),
 PosixPath('data/ifs/20260406/subset_261c582b__20260406000000-48h-oper-fc.grib2'),
 PosixPath('data/ifs/20260406/subset_26322961__20260406000000-66h-oper-fc.grib2'),
 PosixPath('data/ifs/20260406/subset_2689064c__20260406000000-18h-oper-fc.grib2'),
 PosixPath('data/ifs/20260406/subset_26e75169__20260406000000-42h-oper-fc.grib2')]

In [308]:
ds = xr.open_mfdataset(filepath, combine='nested', concat_dim='valid_time')

Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260406/subset_26efdb49__20260406000000-0h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260406/subset_26b20944__20260406000000-6h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260406/subset_26f10269__20260406000000-72h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260406/subset_260eb94f__20260406000000-24h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260406/subset_26059fc2__20260406000000-84h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260406/subset_265ef177__20260406000000-78h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260406/subset_2660db0e__20260406000000-30h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260406/subset_26436d03__20260406000000-60h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260406/subset_260e9787__20260406000000-36h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260406/subset_2612d2a6__20260406000000-12h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260406/subset_2678e5f3__20260406000000-54h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260406/subset_261c582b__20260406000000-48h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260406/subset_26322961__20260406000000-66h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260406/subset_2689064c__20260406000000-18h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260406/subset_26e75169__20260406000000-42h-oper-fc.grib2.5b7b6.idx' older than GRIB file
/tmp/ipykernel_3923274/820905488.py:1: FutureWarning: In a future version of xarray the default value for coords will change from coords='different' to coords='minimal'. This is likely to lead to different results when multiple datasets have matching variables with overlapping values. To opt in to new defaults and get rid of these warnings now use `set_options(use_new_combine_kwarg_defaults=True) or set coords explicitly.
  ds = xr.open_mfdataset(filepath, combine='nested', concat_dim='valid_time')

In [309]:
ds

<xarray.Dataset> Size: 249MB
Dimensions:            (valid_time: 15, latitude: 721, longitude: 1440)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 120B 2026-04-06 ... 2026-0...
  * latitude           (latitude) float64 6kB 90.0 89.75 89.5 ... -89.75 -90.0
  * longitude          (longitude) float64 12kB -180.0 -179.8 ... 179.5 179.8
    time               datetime64[ns] 8B 2026-04-06
    step               (valid_time) timedelta64[ns] 120B 0 days 00:00:00 ... ...
    heightAboveGround  float64 8B 2.0
    surface            float64 8B 0.0
Data variables:
    d2m                (valid_time, latitude, longitude) float32 62MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    tp                 (valid_time, latitude, longitude) float32 62MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    sf                 (valid_time, latitude, longitude) float32 62MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    t2m                (valid_time, latitude, longitude) float32 62MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-04-08T17:31 GRIB to CDM+CF via cfgrib-0.9.1...

In [310]:
# May be necessary to ensure data is in the correct order
ds = ds.sortby('valid_time')
ds

<xarray.Dataset> Size: 249MB
Dimensions:            (valid_time: 15, latitude: 721, longitude: 1440)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 120B 2026-04-06 ... 2026-0...
  * latitude           (latitude) float64 6kB 90.0 89.75 89.5 ... -89.75 -90.0
  * longitude          (longitude) float64 12kB -180.0 -179.8 ... 179.5 179.8
    time               datetime64[ns] 8B 2026-04-06
    step               (valid_time) timedelta64[ns] 120B 0 days 00:00:00 ... ...
    heightAboveGround  float64 8B 2.0
    surface            float64 8B 0.0
Data variables:
    d2m                (valid_time, latitude, longitude) float32 62MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    tp                 (valid_time, latitude, longitude) float32 62MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    sf                 (valid_time, latitude, longitude) float32 62MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    t2m                (valid_time, latitude, longitude) float32 62MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-04-08T17:31 GRIB to CDM+CF via cfgrib-0.9.1...

In [311]:
# Always clip your data to area of interest before saving
ds1 = ds.sel(latitude=slice(42.3,39.7), longitude=slice(-80.6,-74.7))
ds1

<xarray.Dataset> Size: 64kB
Dimensions:            (valid_time: 15, latitude: 11, longitude: 24)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 120B 2026-04-06 ... 2026-0...
  * latitude           (latitude) float64 88B 42.25 42.0 41.75 ... 40.0 39.75
  * longitude          (longitude) float64 192B -80.5 -80.25 ... -75.0 -74.75
    time               datetime64[ns] 8B 2026-04-06
    step               (valid_time) timedelta64[ns] 120B 0 days 00:00:00 ... ...
    heightAboveGround  float64 8B 2.0
    surface            float64 8B 0.0
Data variables:
    d2m                (valid_time, latitude, longitude) float32 16kB dask.array<chunksize=(1, 11, 24), meta=np.ndarray>
    tp                 (valid_time, latitude, longitude) float32 16kB dask.array<chunksize=(1, 11, 24), meta=np.ndarray>
    sf                 (valid_time, latitude, longitude) float32 16kB dask.array<chunksize=(1, 11, 24), meta=np.ndarray>
    t2m                (valid_time, latitude, longitude) float32 16kB dask.array<chunksize=(1, 11, 24), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-04-08T17:31 GRIB to CDM+CF via cfgrib-0.9.1...

In [312]:
# Save as a netcdf file
# If the file already exists, delete it before tying again, otherwise you will see an error
fname = f'AprCalmVarecmwf_{run:%Y%m%d%h}.nc'
ds1.to_netcdf(fname)

In [293]:
ds_a = xr.open_dataset("CalmApril06ecmwf_20260406Apr.nc")
ds_a

sh: 1: getfattr: not found

<xarray.Dataset> Size: 64kB
Dimensions:            (valid_time: 15, latitude: 11, longitude: 24)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 120B 2026-04-06 ... 2026-0...
  * latitude           (latitude) float64 88B 42.25 42.0 41.75 ... 40.0 39.75
  * longitude          (longitude) float64 192B -80.5 -80.25 ... -75.0 -74.75
    time               datetime64[ns] 8B ...
    step               (valid_time) timedelta64[ns] 120B ...
    heightAboveGround  float64 8B ...
    surface            float64 8B ...
Data variables:
    d2m                (valid_time, latitude, longitude) float32 16kB ...
    tp                 (valid_time, latitude, longitude) float32 16kB ...
    sf                 (valid_time, latitude, longitude) float32 16kB ...
    t2m                (valid_time, latitude, longitude) float32 16kB ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-04-08T17:14 GRIB to CDM+CF via cfgrib-0.9.1...

In [153]:
ds_b = xr.open_dataset("ecmwf_20260323Mar.nc")

ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'h5netcdf', 'scipy', 'cfgrib', 'cfradial1', 'datamet', 'furuno', 'gamic', 'gini', 'hpl', 'iris', 'metek', 'nexradlevel2', 'odim', 'rainbow', 'uf']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html

In [ ]:
ds_merge = xr.merge([ds_a, ds_b], compat = 'override')
ds_merge.to_netcdf(

In [ ]:
ds_merge.t2m.isel(valid_time = 1).plot()

# M2 Part 4

In [50]:
#calm day
run2 = pd.Timestamp("2026-04-06-00", tz="utc").replace(tzinfo=None).floor('24h')

In [51]:
H2 = Herbie(run2, model="ifs", product="oper", fxx=6, save_dir='./data/', overwrite=True)

✅ Found ┊ model=ifs ┊ product=oper ┊ 2026-Apr-06 00:00 UTC F06 ┊ GRIB2 @ google ┊ IDX @ google

In [52]:
table2=H2.inventory()

Downloading inventory file from self.idx='https://storage.googleapis.com/ecmwf-open-data/20260406/00z/ifs/0p25/oper/20260406000000-6h-oper-fc.index'

In [53]:
sscalm = "10fg"

In [54]:
H2.inventory(sscalm)

,grib_message,start_byte,end_byte,range,reference_time,valid_time,step,param,levelist,levtype,number,domain,expver,class,type,stream,search_this
16,17,10533589,11953800,10533589-11953800,2026-04-06,2026-04-06 06:00:00,0 days 06:00:00,10fg,NaN,sfc,NaN,g,0001,od,fc,oper,:10fg:sfc:g:0001:od:fc:oper

In [48]:
fp2 = H2.download(sscalm)
fp2

[PosixPath('data/ifs/20260323/subset_aaef3760__20260323000000-0h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aab283c9__20260323000000-6h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa6083c9__20260323000000-30h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa7858ca__20260323000000-54h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aaf13506__20260323000000-72h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa4324ee__20260323000000-60h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa123506__20260323000000-12h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa1c3506__20260323000000-48h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aae758ca__20260323000000-42h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa0e24ee__20260323000000-36h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa0558ca__20260323000000-84h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa898a0a__20260323000000-18h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa3224ee__20260323000000-66h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa0e8a0a__20260323000000-24h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa5e58ca__20260323000000-78h-oper-fc.grib2')]

In [49]:
dscalm = xr.open_dataset(fp2)
dscalm

ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'h5netcdf', 'scipy', 'cfgrib', 'cfradial1', 'datamet', 'furuno', 'gamic', 'gini', 'hpl', 'iris', 'metek', 'nexradlevel2', 'odim', 'rainbow', 'uf']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html

In [37]:
filenamecalm = 'ecmwf_calm10fg.nc'
dscalm.to_netcdf(filenamecalm)

In [38]:
H2 = FastHerbie([run], model="ifs", product="oper", fxx=np.arange(0,90,6).tolist(), save_dir='./data/', overwrite=True)

In [39]:
filepath2 = H2.download(sscalm)
filepath2

[PosixPath('data/ifs/20260323/subset_aa1c3506__20260323000000-48h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aaef3760__20260323000000-0h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa0558ca__20260323000000-84h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aab283c9__20260323000000-6h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa7858ca__20260323000000-54h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa6083c9__20260323000000-30h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa0e8a0a__20260323000000-24h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aae758ca__20260323000000-42h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa4324ee__20260323000000-60h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aaf13506__20260323000000-72h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa123506__20260323000000-12h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa898a0a__20260323000000-18h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa0e24ee__20260323000000-36h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa3224ee__20260323000000-66h-oper-fc.grib2'),
 PosixPath('data/ifs/20260323/subset_aa5e58ca__20260323000000-78h-oper-fc.grib2')]

In [40]:
dscalm = xr.open_mfdataset(filepath2, combine='nested', concat_dim='valid_time')

Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260323/subset_aa1c3506__20260323000000-48h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260323/subset_aaef3760__20260323000000-0h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260323/subset_aa0558ca__20260323000000-84h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260323/subset_aab283c9__20260323000000-6h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260323/subset_aa7858ca__20260323000000-54h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260323/subset_aa6083c9__20260323000000-30h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260323/subset_aa0e8a0a__20260323000000-24h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260323/subset_aae758ca__20260323000000-42h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260323/subset_aa4324ee__20260323000000-60h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260323/subset_aaf13506__20260323000000-72h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260323/subset_aa123506__20260323000000-12h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260323/subset_aa898a0a__20260323000000-18h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260323/subset_aa0e24ee__20260323000000-36h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260323/subset_aa3224ee__20260323000000-66h-oper-fc.grib2.5b7b6.idx' older than GRIB file
Ignoring index file '/courses/meteo473/sp26/473_sp26_group7/data/ifs/20260323/subset_aa5e58ca__20260323000000-78h-oper-fc.grib2.5b7b6.idx' older than GRIB file
/tmp/ipykernel_3923274/1748693493.py:1: FutureWarning: In a future version of xarray the default value for coords will change from coords='different' to coords='minimal'. This is likely to lead to different results when multiple datasets have matching variables with overlapping values. To opt in to new defaults and get rid of these warnings now use `set_options(use_new_combine_kwarg_defaults=True) or set coords explicitly.
  dscalm = xr.open_mfdataset(filepath2, combine='nested', concat_dim='valid_time')

In [42]:
# May be necessary to ensure data is in the correct order
dscalm = dscalm.sortby('valid_time')
dscalm

<xarray.Dataset> Size: 62MB
Dimensions:            (valid_time: 15, latitude: 721, longitude: 1440)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 120B 2026-03-23 ... 2026-0...
  * latitude           (latitude) float64 6kB 90.0 89.75 89.5 ... -89.75 -90.0
  * longitude          (longitude) float64 12kB -180.0 -179.8 ... 179.5 179.8
    time               datetime64[ns] 8B 2026-03-23
    step               (valid_time) timedelta64[ns] 120B 0 days 00:00:00 ... ...
    heightAboveGround  float64 8B 10.0
Data variables:
    fg10               (valid_time, latitude, longitude) float32 62MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-04-08T17:02 GRIB to CDM+CF via cfgrib-0.9.1...

In [43]:
# Always clip your data to area of interest before saving
dscalm2 = dscalm.sel(latitude=slice(42.3,39.7), longitude=slice(-80.6,-74.7))
dscalm2

<xarray.Dataset> Size: 16kB
Dimensions:            (valid_time: 15, latitude: 11, longitude: 24)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 120B 2026-03-23 ... 2026-0...
  * latitude           (latitude) float64 88B 42.25 42.0 41.75 ... 40.0 39.75
  * longitude          (longitude) float64 192B -80.5 -80.25 ... -75.0 -74.75
    time               datetime64[ns] 8B 2026-03-23
    step               (valid_time) timedelta64[ns] 120B 0 days 00:00:00 ... ...
    heightAboveGround  float64 8B 10.0
Data variables:
    fg10               (valid_time, latitude, longitude) float32 16kB dask.array<chunksize=(1, 11, 24), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-04-08T17:02 GRIB to CDM+CF via cfgrib-0.9.1...

In [44]:
# Save as a netcdf file
# If the file already exists, delete it before tying again, otherwise you will see an error
fname2 = f'ecmwf_{run2:%Y%m%d%h}10fg.nc'
dscalm2.to_netcdf(fname2)

In [101]:
ds_calm = xr.open_dataset("ecmwf_20260406Apr.nc")

sh: 1: getfattr: not found

In [45]:
ds_a = xr.open_dataset("ecmwf_20260406Apr.nc")
ds_b = xr.open_dataset("ecmwf_20260406Apr10fg.nc")
ds2 = xr.merge([ds_a, ds_b], compat = 'override')
ds2

sh: 1: getfattr: not found
sh: 1: getfattr: not found

<xarray.Dataset> Size: 80kB
Dimensions:            (valid_time: 15, latitude: 11, longitude: 24)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 120B 2026-03-23 ... 2026-0...
  * latitude           (latitude) float64 88B 42.25 42.0 41.75 ... 40.0 39.75
  * longitude          (longitude) float64 192B -80.5 -80.25 ... -75.0 -74.75
    time               datetime64[ns] 8B ...
    step               (valid_time) timedelta64[ns] 120B ...
    heightAboveGround  float64 8B ...
    surface            float64 8B ...
Data variables:
    d2m                (valid_time, latitude, longitude) float32 16kB ...
    tp                 (valid_time, latitude, longitude) float32 16kB ...
    sf                 (valid_time, latitude, longitude) float32 16kB ...
    t2m                (valid_time, latitude, longitude) float32 16kB ...
    fg10               (valid_time, latitude, longitude) float32 16kB ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-04-06T16:52 GRIB to CDM+CF via cfgrib-0.9.1...