In [1]:
import os

valid_files = [
    f for f in files
    if os.path.exists(f) and os.path.getsize(f) > 10000
]

print(f"✅ Valid files: {len(valid_files)}")

# Show a few
for f in valid_files[:5]:
    print(f)

NameError: name 'files' is not defined

In [18]:
from herbie import Herbie
import pandas as pd
import os
from herbie import Herbie, FastHerbie
import pandas as pd, numpy as np
import xarray as xr
import dask

# -----------------------------
# SETTINGS
# -----------------------------
dt = pd.Timestamp("2026-03-16 18:00")
fxx = range(1, 13)   # shorter range for testing

data_dir = "href_data"

files = []

# -----------------------------
# DOWNLOAD LOOP
# -----------------------------
for f in fxx:
    try:
        H = Herbie(
            dt,
            model="ifs",          # 🔥 SWITCHED MODEL
            product="oper",         # surface fields
            fxx=f,
            save_dir=data_dir
        )

        file = H.download()

        if file and os.path.exists(file):
            files.append(file)
            print(f"✅ f{f:02d} downloaded")
        else:
            print(f"❌ f{f:02d} missing")

    except Exception as e:
        print(f"⛔ f{f:02d} error:", e)

print(f"\n📦 Total files: {len(files)}")

🦨 GRIB2 file not found: self.model='ifs' self.date=Timestamp('2026-03-16 18:00:00') self.fxx=1

💔 Did not find ┊ model=ifs ┊ product=oper ┊ 2026-Mar-16 18:00 UTC F01
❌ f01 missing

🦨 GRIB2 file not found: self.model='ifs' self.date=Timestamp('2026-03-16 18:00:00') self.fxx=2

💔 Did not find ┊ model=ifs ┊ product=oper ┊ 2026-Mar-16 18:00 UTC F02
❌ f02 missing
✅ Found ┊ model=ifs ┊ product=oper ┊ 2026-Mar-16 18:00 UTC F03 ┊ GRIB2 @ local ┊ IDX @ azure-scda
✅ f03 downloaded

🦨 GRIB2 file not found: self.model='ifs' self.date=Timestamp('2026-03-16 18:00:00') self.fxx=4

💔 Did not find ┊ model=ifs ┊ product=oper ┊ 2026-Mar-16 18:00 UTC F04
❌ f04 missing

🦨 GRIB2 file not found: self.model='ifs' self.date=Timestamp('2026-03-16 18:00:00') self.fxx=5

💔 Did not find ┊ model=ifs ┊ product=oper ┊ 2026-Mar-16 18:00 UTC F05
❌ f05 missing
✅ Found ┊ model=ifs ┊ product=oper ┊ 2026-Mar-16 18:00 UTC F06 ┊ GRIB2 @ local ┊ IDX @ azure-scda
✅ f06 downloaded

🦨 GRIB2 file not found: self.model='ifs' self.date=Timestamp('2026-03-16 18:00:00') self.fxx=7

💔 Did not find ┊ model=ifs ┊ product=oper ┊ 2026-Mar-16 18:00 UTC F07
❌ f07 missing

🦨 GRIB2 file not found: self.model='ifs' self.date=Timestamp('2026-03-16 18:00:00') self.fxx=8

💔 Did not find ┊ model=ifs ┊ product=oper ┊ 2026-Mar-16 18:00 UTC F08
❌ f08 missing
✅ Found ┊ model=ifs ┊ product=oper ┊ 2026-Mar-16 18:00 UTC F09 ┊ GRIB2 @ local ┊ IDX @ azure-scda
✅ f09 downloaded

🦨 GRIB2 file not found: self.model='ifs' self.date=Timestamp('2026-03-16 18:00:00') self.fxx=10

💔 Did not find ┊ model=ifs ┊ product=oper ┊ 2026-Mar-16 18:00 UTC F10
❌ f10 missing

🦨 GRIB2 file not found: self.model='ifs' self.date=Timestamp('2026-03-16 18:00:00') self.fxx=11

💔 Did not find ┊ model=ifs ┊ product=oper ┊ 2026-Mar-16 18:00 UTC F11
❌ f11 missing
✅ Found ┊ model=ifs ┊ product=oper ┊ 2026-Mar-16 18:00 UTC F12 ┊ GRIB2 @ local ┊ IDX @ azure-scda
✅ f12 downloaded

📦 Total files: 4

In [3]:
valid_files = [
    f for f in files
    if os.path.exists(f) and os.path.getsize(f) > 10000
]

print(f"✅ Valid files: {len(valid_files)}")

✅ Valid files: 12

In [4]:
H.inventory()

,grib_message,start_byte,end_byte,range,reference_time,valid_time,variable,level,forecast_time,search_this
0,1,0,718371.0,0-718371,2026-03-16 18:00:00,2026-03-17 06:00:00,REFC,entire atmosphere,12 hour fcst,:REFC:entire atmosphere:12 hour fcst
1,2,718372,1084118.0,718372-1084118,2026-03-16 18:00:00,2026-03-17 06:00:00,RETOP,cloud top,12 hour fcst,:RETOP:cloud top:12 hour fcst
2,3,1084119,1846301.0,1084119-1846301,2026-03-16 18:00:00,2026-03-17 06:00:00,var discipline=0 center=7 local_table=1 parmca...,entire atmosphere,12 hour fcst,:var discipline=0 center=7 local_table=1 parmc...
3,4,1846302,2253247.0,1846302-2253247,2026-03-16 18:00:00,2026-03-17 06:00:00,VIL,entire atmosphere,12 hour fcst,:VIL:entire atmosphere:12 hour fcst
4,5,2253248,3736682.0,2253248-3736682,2026-03-16 18:00:00,2026-03-17 06:00:00,VIS,surface,12 hour fcst,:VIS:surface:12 hour fcst
...,...,...,...,...,...,...,...,...,...,...
168,169,149485581,149503811.0,149485581-149503811,2026-03-16 18:00:00,2026-03-17 06:00:00,ICEC,surface,12 hour fcst,:ICEC:surface:12 hour fcst
169,170,149503812,151252070.0,149503812-151252070,2026-03-16 18:00:00,2026-03-17 06:00:00,SBT123,top of atmosphere,12 hour fcst,:SBT123:top of atmosphere:12 hour fcst
170,171,151252071,153719214.0,151252071-153719214,2026-03-16 18:00:00,2026-03-17 06:00:00,SBT124,top of atmosphere,12 hour fcst,:SBT124:top of atmosphere:12 hour fcst
171,172,153719215,155290601.0,153719215-155290601,2026-03-16 18:00:00,2026-03-17 06:00:00,SBT113,top of atmosphere,12 hour fcst,:SBT113:top of atmosphere:12 hour fcst
172,173,155290602,NaN,155290602-,2026-03-16 18:00:00,2026-03-17 06:00:00,SBT114,top of atmosphere,12 hour fcst,:SBT114:top of atmosphere:12 hour fcst

In [5]:
ss = r":REFC:"

In [6]:
H.inventory(ss)

,grib_message,start_byte,end_byte,range,reference_time,valid_time,variable,level,forecast_time,search_this
0,1,0,718371.0,0-718371,2026-03-16 18:00:00,2026-03-17 06:00:00,REFC,entire atmosphere,12 hour fcst,:REFC:entire atmosphere:12 hour fcst

In [15]:
# search strings can be complicated regular expressions to match multiple parameters at once
# height, temperature, and wind on mandatory levels
ss2 = ":REFC:"
H.xarray("REFC")

#H.inventory(ss2)

/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:1280: UserWarning: Will not remove GRIB file because it previously existed.
  warnings.warn("Will not remove GRIB file because it previously existed.")

<xarray.Dataset> Size: 38MB
Dimensions:              (y: 1059, x: 1799)
Coordinates:
    time                 datetime64[ns] 8B 2026-03-16T18:00:00
    step                 timedelta64[ns] 8B 12:00:00
    atmosphere           float64 8B 0.0
    latitude             (y, x) float64 15MB ...
    longitude            (y, x) float64 15MB ...
    valid_time           datetime64[ns] 8B ...
    gribfile_projection  object 8B None
Dimensions without coordinates: y, x
Data variables:
    refc                 (y, x) float32 8MB ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    model:                   hrrr
    product:                 sfc
    description:             High-Resolution Rapid Refresh - CONUS
    remote_grib:             href_data/hrrr/20260316/hrrr.t18z.wrfsfcf12.grib2
    local_grib:              href_data/hrrr/20260316/subset_1312795e__hrrr.t1...
    search:                  REFC

In [8]:
fp = H.download(ss2)

In [9]:
fp

PosixPath('href_data/hrrr/20260316/subset_1312795e__hrrr.t18z.wrfsfcf12.grib2')

In [10]:
ds = xr.open_dataset(fp)
ds

<xarray.Dataset> Size: 38MB
Dimensions:     (y: 1059, x: 1799)
Coordinates:
    time        datetime64[ns] 8B ...
    step        timedelta64[ns] 8B ...
    atmosphere  float64 8B ...
    latitude    (y, x) float64 15MB ...
    longitude   (y, x) float64 15MB ...
    valid_time  datetime64[ns] 8B ...
Dimensions without coordinates: y, x
Data variables:
    refc        (y, x) float32 8MB ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2026-03-23T15:36 GRIB to CDM+CF via cfgrib-0.9.1...

In [11]:
ss3 = ":VIS:"
H.inventory(ss3)

,grib_message,start_byte,end_byte,range,reference_time,valid_time,variable,level,forecast_time,search_this
4,5,2253248,3736682.0,2253248-3736682,2026-03-16 18:00:00,2026-03-17 06:00:00,VIS,surface,12 hour fcst,:VIS:surface:12 hour fcst

In [12]:
fv = H.download(ss3)

In [13]:
dv = xr.open_dataset(fv)
dv

<xarray.Dataset> Size: 38MB
Dimensions:     (y: 1059, x: 1799)
Coordinates:
    time        datetime64[ns] 8B ...
    step        timedelta64[ns] 8B ...
    surface     float64 8B ...
    latitude    (y, x) float64 15MB ...
    longitude   (y, x) float64 15MB ...
    valid_time  datetime64[ns] 8B ...
Dimensions without coordinates: y, x
Data variables:
    vis         (y, x) float32 8MB ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2026-03-23T15:36 GRIB to CDM+CF via cfgrib-0.9.1...